version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: docker\Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - monitor

  monitor:
    build:
      context: .
      dockerfile: docker\Dockerfile.monitor
    ports:
      - "8001:8001"

  finetune:
    build:
      context: .
      dockerfile: docker\Dockerfile.finetune
    volumes:
      - ./models:/app/models